language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-26.0.2
    - android-25
    - extra-android-support
    - extra-android-m2repository

    - android-21
    - sys-img-x86-android-21

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - cp ./google-licenses/* "$ANDROID_HOME/licenses/"

script:
  - echo no | android create avd --force -n test -t android-21 --abi x86
  - emulator -avd test -memory 1500 -no-accel -gpu swiftshader -camera-back none -camera-front none -no-boot-anim -no-snapshot-save -no-snapstorage
  - ./gradlew clean app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.forrestguice.suntimeswidget.SuntimesResTest
