language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-26.0.2
    - android-25
    - extra-android-support
    - extra-android-m2repository

    - android-22
    - sys-img-x86-android-22

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - cp ./google-licenses/* "$ANDROID_HOME/licenses/"

before_script:

  - rm -rf $ANDROID_HOME/emulator
  - cd $ANDROID_HOME

   if [ $TRAVIS_OS_NAME == "osx" ]; then
      wget -q "https://dl.google.com/android/repository/emulator-darwin-5346014.zip" -O emulator.zip
    else
      sudo apt-get install -y libunwind8 libc++1
      wget -q "https://dl.google.com/android/repository/emulator-linux-5346014.zip" -O emulator.zip
    fi
  - unzip -q emulator.zip
  - cd -

  - echo no | android create avd --force -n test -k "system-images;android-22;default;x86_64"
  - emulator-headless -avd test -no-boot-anim -gpu off -no-audio -no-accel &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.forrestguice.suntimeswidget.SuntimesResTest
