language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-26.0.2
    - android-25
    - extra-android-support
    - extra-android-m2repository

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - cp ./google-licenses/* "$ANDROID_HOME/licenses/"

before_script:
  - echo no | android create avd --force -n test -t android-25 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.forrestguice.suntimeswidget.SuntimesResTest
